### ISSUE TITLE
Termometrar F007 / FT007

### ISSUE THREAD

**Issue by Turtures** [nlrb/com.weather-sensors#10]
Hello Ramón Baas,  could you have the kindness of expanding with a few more thermometers, F007 / FT007 range of products sold under various brand names like Ambient Weather, Frogit, Renkforce, Telldus, Conrad.
They must be similar to that of Patrik Brodd you fixed. 
I have some different. One is F007TPH where I see the outdoor temperature but not the indoor temperature

**Comment by nlrb** [comment]
Can you provide some more information (i.e. a link to the sensor, the protocol)? I cannot find a F007TPH sensor with Google. And how could one sensor measure indoor & outdoor temperature at the same time?

**Comment by Turtures** [comment]
http://telldus.com/produkt/inneute-termohygro-sensor-433mhz/
http://telldus.com/produkt-kategori/sensors-en/

**Comment by nlrb** [comment]
Looking at the manual, the Telldus app also only shows one temperature: http://www.telldus.com/wp-content/uploads/312203_Manual_Ver1.2_160902_Web.pdf ('8'). So
a) what do you see now (screenshots help)?
b) what do you expect to see?

And which version of the app are you using?

**Comment by Turtures** [comment]
Hello again 
Now I did a reinstallation of the app v1.2.2 and suddenly all the sensors appeared :-) . Anyway, the channels are displayed incorrectly. they should show 1-5. They go off line all the time but come back. And i see one is missing so far the Conservatory outdoor. As I see it, work is already done, except that the channels are displayed incorrectly

![homey sensors](https://user-images.githubusercontent.com/32330648/30974225-6fec6032-a46f-11e7-8a7e-6b99380fafdb.png)
/Tom D

**Comment by Turtures** [comment]
Här ser du hur det såg ut i Telldus som nu är avvecklad
![telldus sensors](https://user-images.githubusercontent.com/32330648/30975388-74acfa7a-a472-11e7-83a2-1470d8ee4471.png)

**Comment by nlrb** [comment]
Could it be it doesn't send the channel setting in the data? Can you download statistics and attach the json file?

**Comment by Turtures** [comment]
I think you're right, if you look at Telldus gif, you do not see the channels just id
[stats1506667193108.zip](https://github.com/nlrb/com.weather-sensors/files/1343323/stats1506667193108.zip)

**Comment by nlrb** [comment]
Which sensor ID is on which channel?

**Comment by Turtures** [comment]
id 135 & 147 ch1
id 8 ch2
id 167 ch3
id 199 ch5
id 247 & 19 ch8

**Comment by Turtures** [comment]
[stats1506697554516.zip](https://github.com/nlrb/com.weather-sensors/files/1344798/stats1506697554516.zip)

**Comment by nlrb** [comment]
Can you download and test the latest version of the code and check it is OK now (incl. channel)?

**Comment by Turtures** [comment]
![homey sensors 2](https://user-images.githubusercontent.com/32330648/31044613-e57f5b9c-a5d2-11e7-8779-1ca63591065c.png)

**Comment by Turtures** [comment]
strange id19 auriol but id248 Alecto v3 both F007TPH

**Comment by nlrb** [comment]
I don't know your sensors, but they are really different protocols (different timings and one uses 36 bits and the other 40 bits of data).

**Comment by Turtures** [comment]
China China & China :-) But I think many will be happy when these Telldus thermometers work, and I hope they reward you for your work

**Comment by Turtures** [comment]
Thank you

**Comment by Graphicalmarc** [comment]
I'm also interested in these sensors to be working. These sensors are quite common in Sweden. Hope to see these sensors working in the near future. Cheers
