### ISSUE TITLE
Ver 3.10, problem with Alecto v3

### ISSUE THREAD

**Issue by hi-jo** [nlrb/com.weather-sensors#104]
I have three temp/humidity sensors. After update to 3.1.0 the one on ch1 started giving strange temp values, 40C below the actual temperature. Sensors on ch2 & ch3 stopped updating completely.

I see that each update from the sensor gives two messages in the app, one with device type WS-1100 and one with device type WH2, both have the same id but the one with type WS-1100 always show ch as 1 while the WH2 message has the right ch. The message for WS-1100 also have the incorrect temperature.
![image](https://user-images.githubusercontent.com/53565985/236137613-5515d5e4-8249-43cf-8a44-1e7c3a271b6e.png)

All devices were removed and the app restarted. I was then able to pair ch1 once but still got the wrong temperature, sensors on ch2 and ch3 was not possible to pair and a second attempt at pairing ch1 failed.

**Comment by hi-jo** [comment]
I saw the release notes, but I didn't know if it was relevant for my sensors or not, I take it then that my sensors use the FineOffset protocol.
As it is, nothing shows up in the app when trying to pair, neither WS-1100 nor WH2, and I only see them pop up briefly in the list of available sensors that I screenshot earlier. Perhaps that's normal, don't remember how it was before.
Additional details, this is on a Homey (Early 2019) device running firmware 8.1.3
The "trade name" for the sensor is Telldus 313160, but I suspect it's sold under a number of different names.
If there's any other information that may aid in troubleshooting I'll try to help.

**Comment by juw2** [comment]
I have the same issue on Homey Pro (Early 2023) RC.98.
If I install an older version (cli-install) then it works. Something happened with version 3.10.
I can't pair any more and if I pair with the old version I get an exclamation mark on them.

**Comment by nlrb** [comment]
@hi-jo Since you mention that 'I only see them pop up briefly in the list of available sensors', I guess the issue is related to date/time changes that were needed for v3. Likely it interprets the time wrongly and will remove the sensor from the list again right away.

As a workaround it may help to change the setting to marking it unavailable to 1 day for the moment.

Which language (locale) and timezone is your Homey on?

**Comment by hi-jo** [comment]
Indeed, changing to one day worked, then I could pair the sensors so I think you're on to something.

The language setting is english, timezone is Europe/Stockholm, which should correspond to CET I assume.
