### ISSUE TITLE
Ver 3.1.1 update fails

### ISSUE THREAD

**Issue by Lab-ro** [nlrb/com.weather-sensors#105]
After upgrade to v3.1.1 all termometers stopped working. No temp or humid figures updated after the upgrade. The icon show the same temp/humid for the last 2 days.
Have restarted the Homey, No change

**Comment by glye** [comment]
Same for my 4 units paired as Alecto v3 type WH2. The changelog says of v3.1.0: "Made FineOffset separate protocol within Alectov3 (needs re-pairing)". So I tried "maintenance" -> "try to repair", which shows 4 units of WS-1100 as "New devices found". I select one, "Continue", and then nothing.

**Comment by glye** [comment]
Solved for me. "re-pairing" is not the same as "repairing". I had to re-add (re-pair) the devices, after that they seem to be working fine. I'm keeping the old devices a while to maintain historic data.

**Comment by nlrb** [comment]
@glye Great to hear you found the right procedure indeed. For this update a split has been made in protocols, which means that you really have to delete FineOffset based sensors (Teldus?). From now on you should be able to repair them if needed and keep the history.

**Comment by Lab-ro** [comment]
HejSo Re-pair is the same as add them again creating a new device. Correct?So all my flows needs to be updated with the new devices as well?  Or are there a way to avoid this?Mvh, RogerSent from my Iphone13 maj 2023 kl. 14:04 skrev Ramón Baas ***@***.***>:﻿
@glye Great to hear you found the right procedure indeed. For this update a split has been made in protocols, which means that you really have to delete FineOffset based sensors (Teldus?). From now on you should be able to repair them if needed and keep the history.

**Comment by glye** [comment]
Yes, I have Telldus sensors. Good they are still supported! Thanks.
