### ISSUE TITLE
Some sensors not updated in 5 days

### ISSUE THREAD

**Issue by pertomas** [nlrb/com.weather-sensors#106]
Problems reading some sensors.

I can not read out its Alecto sensors that har stoped working. Restarted the app with no result.

In "Available sensors" sensors seems to work but to when they are presented in Homey.

I have a homey pro, not the latest on.

Per Tomas

**Comment by nlrb** [comment]
That is normal, as described in the release notes. See also #105.

**Comment by pertomas** [comment]
Thanks, reinstalled & reinstalled to make a fresh start. Have worked real great over years.
