### ISSUE TITLE
Alecto v3 sensors unavailable

### ISSUE THREAD

**Issue by dan-sone** [nlrb/com.weather-sensors#107]
Hi,
After the update 3.1.1 all my alecto v3 sensors in homey are unable to receive data. I’d very much like to reassign them to the existing decices, since I both have flows and stats i’d like to keep.
Thankful for advice how to proceed!

Regards,
Dan

**Comment by nlrb** [comment]
You can keep the existing ones for historic data, but will have to pair new ones. See #104 #106.
