### ISSUE TITLE
Problem with multiple OREGON device on the same channel

### ISSUE THREAD

**Issue by MathieuNA** [nlrb/com.weather-sensors#108]
Hello,
I have multiple OREGON device THGR122NX and some are on the same channel (1 to 3). You app in HOMEY is not able to separate these device if they are on the same channel. Could you do something to improve your app?
Thanks and have a nice weekend
Mathieu

**Comment by nlrb** [comment]
How do you expect to distinguish between sensors if you put them on the same channel? The whole reason to have channel settings is to allow multiple sensors…
