### ISSUE TITLE
Humidity not working for Telldus WH2

### ISSUE THREAD

**Issue by n808** [nlrb/com.weather-sensors#109]
After the May 9th update (v3.1.1) the app stopped working for all my Telldus temp and humidity sensors. After re-adding them all, I got temperatures to work again, but not humidity. They are all stuck at 20%. Feel free to close this issue if humidity never worked, but I thought it did, or maybe I don't remember correctly.

**Comment by n808** [comment]
24 hours after I created the issue above, the app has read the correct humidity for one of my four WH2 sensors, while the other three are still stuck at their minimum 20%. - strange. Temperatures are read frequently and correctly,

**Comment by nlrb** [comment]
The humidity decoding did not change. Can it just be dry?

**Comment by n808** [comment]
No, The sensors show the right number on their LCD, 25-27% or so. 
For example, "kitchen" in Homey app shows temp 23.9C - 3 minutes ago, humidity 20% - 3 days ago, which is when I re-added the sensors. LCD 27% humidity. So no humidity updates, temp updates every few minutes. Very strange.

**Comment by nlrb** [comment]
Can you add a screenshot of the app settings where you see the data?

**Comment by n808** [comment]
I think it started working! Perhaps the issue is that humidity changes so very slowly, that the senors do not send out updates very often. But today, all sensors had updated their humidity. Still it was "x _hours_ ago", while temperature was almost _minutes_ ago. I think we can close this issue then. Thanks for following up.

**Comment by n808** [comment]
Closing - not a bug. It might just take a really long time for humidity to start syncing after re-adding sensors.

**Comment by nlrb** [comment]
It is still unclear for me. Humidity data is part of the same payload as temperature. And there is no reason why it should not update. That is unrelated to when a device has been paired. So there must be another reason.

**Comment by nlrb** [comment]
Homey only showes when the value last changed. Not when a value was last received. Indeed temperature is in bits 13-24 en humidity in bits 24-32 of one payload.
