### ISSUE TITLE
Promlem with Homey crashing with app installed

### ISSUE THREAD

**Issue by TobiasEkholm** [nlrb/com.weather-sensors#11]
As soon as i enable or install this app my Homey becomes first sluggish and then in a short period of time unresponsive and then is "Offline" then i have to pull the plug from the homey to reboot it.
I´ve tried to uninstall/install the app and enable/disable the app.
There are also 2700 notifications from the app wich i cannot clear in system settings.

**Comment by nlrb** [comment]
What notifications do you get from the app (2700?). Can you add a screenshot? Also, have you tried to disable the notifications in the app settings?
My assumption would be that there is something corrupted in your Homey notifications. I would advise to contact Athom support to fix this.

**Comment by TobiasEkholm** [comment]
Ok, but are the notifications to be deleted/vanish if i uninstall the app ?  (or is there any way to clear cache from the weather sensor app after uninstalling) In my case the 2700 notification reappears after uninstalling/installing wich seemes strange. I have disabled notifications.

**Comment by nlrb** [comment]
Again, can you post a screenshot or so of the notifications? As far as I know, all app related data should be removed when you delete it. If not, this looks to be a bug in Homey. But I'd also like to understand how you ended up with 2700 notifications.

**Comment by TobiasEkholm** [comment]
![sample_notifications](https://user-images.githubusercontent.com/32663348/31374441-4ae86a6e-ad9e-11e7-83a7-34c06195cedd.JPG)
Here are a screenshot.
![notifications](https://user-images.githubusercontent.com/32663348/31374416-2c21d804-ad9e-11e7-9f63-52abdddf6904.JPG)

**Comment by nlrb** [comment]
So the app has been running for days without an issue (notifications are 8 days old)?
If the issue only occurred after you got so many notifications & you cannot clear them, you need to contact Athom support and have them solve it. This is not something I can solve.

**Comment by nlrb** [comment]
Have you been able to resolve it?

**Comment by TobiasEkholm** [comment]
Hi, yes finaly it’s resolved!
Eventually Homey froze after a minute of uptime with the app installed. I chose to try to delete the notifications (again) and it froze and went Offline. This time i left Homey alone for 24 hours and when i got back Homey was up and running and the notifications gone.

Skickat från min iPhone

**Comment by nlrb** [comment]
Good to hear!
