### ISSUE TITLE
Alecto WS-3500 not showing after migrating from Homey 2016 to Homey pro 2023

### ISSUE THREAD

**Issue by Multied1** [nlrb/com.weather-sensors#116]
Hi Ramón,
First of all thanks for the good work!
Yesterday I received the new Homey 2023, the migration from my old 2016 model went fine but.. I can get the Alecto ws-3500 working anymore. Pulled out the battery's for 1 minute, put the battery's back and try to get a signal.
Any tips in these?
Br Edwin

**Comment by Multied1** [comment]
Goodmorning,

I'm lost, maybe someone can help me. As stated in my earlier post, everything work fine on the homey pro (2016), after the migration to the homey pro 2023 I get no signal at all![image](https://github.com/nlrb/com.weather-sensors/assets/101838865/b14d6953-0bd9-4701-accd-8fec675c7d53) 

Anyone??

**Comment by nlrb** [comment]
Is there anything with 433 that works with your new Homey? Have you considered that it might be defective?

**Comment by Multied1** [comment]
Hi Ramón,
Thanks for your reply. 
Yes all of the Kaku (433) devices (remotes and plugs) and also a doorbell from Alecto at my fence are working fine. 
I've also dismounted the WS-3500 and put it next to the new Homey, pulled out the battery's but no signal unfortunately🤨

**Comment by Multied1** [comment]
Hi Ramón,
Unfortunately the Alecto WS-3500 is still not showing up in the app. Do you have any other solution or suggestion getting it working?
Thanks in advance.
Edwin

**Comment by Multied1** [comment]
Replaced the Alecto, now using Popp zwave.
