### ISSUE TITLE
How to read the Owl cm160 energy monitor 

### ISSUE THREAD

**Issue by byegit** [nlrb/com.weather-sensors#118]
Dear developer 
I own a homey pro and an older CM160 energy monitor from theOwl.com. 
My last Fhem HA read the probe with a RTXTRX433. 

The Owl uses the Oregon Scientific V3 protocol. 
https://www.domoticsduino.cloud/en/blog/iot-smarthome/post/2017/02/rf-433-mhz-data-sniffing.html

Is it possible to read the output also with your Homey App?

Kind regards
Jens

**Comment by byegit** [comment]
Another git repo used to read from the owl energy monitors CM160/180 : https://github.com/onlinux/OWL-CM180

**Comment by nlrb** [comment]
You should be able to read the temperature and humidity values, as the THGR228N is supported.
Reading power values is something you could make work, but not in the scope of this app.
