### ISSUE TITLE
Oregon THGN132N and THGR122N

### ISSUE THREAD

**Issue by ivanpuskas** [nlrb/com.weather-sensors#12]
Hello, I would like to pair three sensors, two THGN132N and one THGR122N ( as a part of O.S. RAR502 ) with Homey with no luck at all.  I can see a communication in debug but nothing else. Thanks for any help you can provide. Thanks a lot. Ivan
[stats1508271232347.txt](https://github.com/nlrb/com.weather-sensors/files/1392478/stats1508271232347.txt)

**Comment by nlrb** [comment]
Sorry for the late reply. There is almost no data in the json file. How long was the app running?

**Comment by Maxwell70** [comment]
Hi! Homey no longer see the sensor THGN132N after the last firmware update. Help!

**Comment by nlrb** [comment]
Yes, I have the same problem. Can you submit an issue with Athom?

**Comment by Maxwell70** [comment]
Today was released the new firmware, but nothing changed. I wrote in support of Athom , but they told me that I should go to the developer.

**Comment by nlrb** [comment]
Do you know who from support said that? The app hasn't changed, it is clearly the firmware. Please submit your ticket here: https://github.com/athombv/homey/issues

**Comment by Maxwell70** [comment]
I wrote there! Before the update Homey is very difficult to see my sensors. I made several restarts of the sensors so Homey saw them.

**Comment by nlrb** [comment]
What is/was your issue number? Can you post the link here?

**Comment by Maxwell70** [comment]
Number what?

**Comment by nlrb** [comment]
The GitHub issue number at Athom (the link I posted). Like this one is \#12, you then should also have a number from the Athom GitHub.

**Comment by Maxwell70** [comment]
https://github.com/athombv/homey/issues/2075
