### ISSUE TITLE
Oregon PCR800 Rain

### ISSUE THREAD

**Issue by huelinb** [nlrb/com.weather-sensors#122]
Not possible to add the sensor.
I have this answer when i tried to add Rain sensor

"Cannot read properties of undefined (reading 'getSensors').

But the Oregon station is near the Homey Pro and is connected with the sensor.

Thank you for your great App. Works rallye fine with wind and Temp/Rh sensors.

**Comment by nlrb** [comment]
I cannot find a stack trace for that. Can you otherwise share a screenshot of the error?

**Comment by huelinb** [comment]
![Screenshot_20230902_220934_Homey](https://github.com/nlrb/com.weather-sensors/assets/8820273/c6a90e9a-e8f0-4e28-b747-98cb77086079)

**Comment by nlrb** [comment]
I've seen this once, but am not able to reproduce it anymore.
Can you restart the app an see if it keeps happening?

**Comment by huelinb** [comment]
Good news!
Just restart the app and now it's working fine for me.
Thank you so much for your time and answer!
