### ISSUE TITLE
Total Rain displayed as m3

### ISSUE THREAD

**Issue by Cubpef** [nlrb/com.weather-sensors#126]
I have a rain meter using the Oregon v3 protocol an of type PCR800. The problem is that total rain is displayed as 0,84 m3, and i would like it to be in mm and one more decimal 840 mm

**Comment by nlrb** [comment]
For total rain the default Homey capability `meter_rain` is used, see https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html. This is defined to use m3. So if you want to change this, Athom would have to change this.
