### ISSUE TITLE
Support for TFA 30.3139

### ISSUE THREAD

**Issue by Conterganer** [nlrb/com.weather-sensors#130]
According to the Wireless Weather Sensors the TFA should be @ Support for TFA 30.3139
Be compatible…
But it doesn’t work.
[
](https://community.homey.app/t/app-pro-wireless-weather-sensors-reads-data-from-several-brands-of-wireless-weather-sensors/23532/167?u=frank62)

**Comment by nlrb** [comment]
Sorry to hear it is not working for you. My 30.3139 is working fine here.

**Comment by Conterganer** [comment]
Ich habe den.
https://www.amazon.de/dp/B001QLEHM4?psc=1
und
Homey Pro
Modell Homey Pro (Early 2023)
Version 10.3.0-rc.7
Wireless Weather Sensors
v3.2.0

![PHOTO-2024-02-01-17-00-38](https://github.com/nlrb/com.weather-sensors/assets/141663492/c3e1a3fd-b05e-4e0f-84bb-d89d7bcb378c)

**Comment by nlrb** [comment]
This is the risk of using experimental firmware. It all works fine on the official firmware.

**Comment by Conterganer** [comment]
Homey Pro
Modell Homey Pro (Early 2023)
Version 10.3.0
Wireless Weather Sensors
v3.2.0
Which version is currently the stable version and which is the test version?
[
](https://community.homey.app/t/app-pro-wireless-weather-sensors-reads-data-from-several-brands-of-wireless-weather-sensors/23532/171)

**Comment by Conterganer** [comment]
> This is the risk of using experimental firmware. It all works fine on the official firmware.

I'm now using the official stable Version 10.3.0 and still nothing works.

**Comment by nlrb** [comment]
I’m using latest version 10.0.6 on Homey Pro (Early 2019) and there it works fine.

**Comment by Conterganer** [comment]
Which version is currently the stable version and which is the test version?

**Comment by Conterganer** [comment]
3cb6d49b-f149-4ee0-8a9e-de7bea97137e

**Comment by nlrb** [comment]
There is only one version active of the app (3.2.0). The code for the 30.3139 was last changed 5 years ago. If it now does not work on the Homey Pro (Early 2023), then I guess Athom has introduced a regression issue in their firmware. Best to take that up with them.

**Comment by Conterganer** [comment]
5 years ago the (Homey Pro Early 2023) didn't exist.

**Comment by ArjanSnijders** [comment]
FYI. Reported at Athom and waiting for a reply.

**Comment by Conterganer** [comment]
[ArjanSnijders](https://github.com/ArjanSnijders) Thank you.

**Comment by ArjanSnijders** [comment]
Athom replied they can't do anything. The code should be made compatible with Homey Pro (Early 2023).
That's not happening in the near future... TFA 30.3139 is herby, not compatible with Homey Pro (Early 2023) in this app.

**Comment by nlrb** [comment]
Can you put the reference to the ticket in? Because this answer is nonsense. The app is compatible with Homey Po 2023. So then they can explain to me what I would need to change (which they will not be able to explain as the code should work the same over both models).

**Comment by ArjanSnijders** [comment]
I got ticket number 121067 from them. Is that enough for you?

**Comment by nlrb** [comment]
Thanks @ArjanSnijders, I will contact Athom.

FYI - I ran a comparision with Homey Pro 2019 & Homey Pro 2023. Both Homeys were in the same location and the app started the same time. After running for ~half a day it gives the following results:
### Homey Pro 2019
<img width="362" alt="Screenshot 2024-05-20 at 09 04 55" src="https://github.com/nlrb/com.weather-sensors/assets/11725674/9ab2f16f-a3a1-4d34-814c-afabbad0de01">

### Homey Pro 2023
<img width="362" alt="Screenshot 2024-05-20 at 09 05 03" src="https://github.com/nlrb/com.weather-sensors/assets/11725674/40ee579e-ff1e-42ab-8e0b-53c736561588">

_(Note: no LaCrosse devices were active during testing)_

As you can see, 433 MHz signal reception processing on Homey Pro 2023 is just very poor. Most signals are not received/processed properly.

**Comment by nlrb** [comment]
[SDK issue 347](https://github.com/athombv/homey-apps-sdk-issues/issues/347) submitted with Athom.

**Comment by Conterganer** [comment]
Nothing still works here.

**Comment by nlrb** [comment]
@Conterganer Better to comment on https://github.com/athombv/homey-apps-sdk-issues/issues/347.
