### ISSUE TITLE
App not getting installed on Homey pro 2023

### ISSUE THREAD

**Issue by ricercar07** [nlrb/com.weather-sensors#132]
Hello,
I have 2 Homey pro 2023 and the app doesn't get installed on both of them though it says that it will be installed.
I have rebooted both Homeys to no avail. First time I have this problem installing apps.

Cheers

John

**Comment by nlrb** [comment]
Hi John,

Sorry to hear that. It is best to contact Athom about that. There is nothing that I can do from the app side on that.

Grtz,
-Ramón
