### ISSUE TITLE
TS808 temperature data not connected

### ISSUE THREAD

**Issue by StijnDamen** [nlrb/com.weather-sensors#134]
The TS808 sensor was added to the system, and in the configuration page i can see the RAW string which starts with temperature: 13. So the data is comming to the homey, but in the device it self the temperature options stays empty.
Maybe a missing link? Please let me know if you would like extra information or a configuration file.

**Comment by StijnDamen** [comment]
97783254-e5db-427d-a32b-421574bf113b

**Comment by nlrb** [comment]
Can you add some screenshots of what you see? Did you try to restart the app?

**Comment by StijnDamen** [comment]
![meter 3](https://github.com/nlrb/com.weather-sensors/assets/132998746/558f3b44-bb50-444b-9b13-3d62c0e16bb2)
![meter 2](https://github.com/nlrb/com.weather-sensors/assets/132998746/d4487cc1-c5ff-4a78-9621-5f2292171a29)
![meter 1](https://github.com/nlrb/com.weather-sensors/assets/132998746/8a367e42-a611-4b80-8b02-1729a739c34d)

I just restarted the app, seems to make no difference. If i hoover over the information of the device i do see that all values are updated recently(between 8 and 1 minute), and the temperature says 2u ago. 

And would it be possible to rename the device? 

Thanks in advance!

**Comment by nlrb** [comment]
Thanks. I see what the issue is, will fix this (the calculation is missing brackets which makes the result to be a string instead of a number).

**Comment by nlrb** [comment]
Can you check if it is fixed in the test version: https://homey.app/en-md/app/com.weather-sensors/Wireless-Weather-Sensors/test/ ?

**Comment by StijnDamen** [comment]
Yes, looks like it is working perfectly. I did had to remove the device and add it again to homey. Thank you so much for the fast and accurate bugfix!!Groeten,Stijn DamenVerstuurd vanaf mijn iPhoneOp 10 mrt 2024 om 20:43 heeft Ramón Baas ***@***.***> het volgende geschreven:﻿
Can you check if it is fixed in the test version: https://homey.app/en-md/app/com.weather-sensors/Wireless-Weather-Sensors/test/ ?
