### ISSUE TITLE
Able to change in the units for total rain.

### ISSUE THREAD

**Issue by Roadrunner-Blue** [nlrb/com.weather-sensors#143]
Hi,
I have used the Wireless Weather Sensors for a long time now and it works fine as so far but I have some question about setting of units and decimals of one rain sensor.
I have a Telldus weather station as uses your app to connect in my latest Homey Pro (2023) with the Oregon Scientific v3 protocol.
As the units in total rain is in m3 units and only 2 decimals, it is very hard to see a 24 hours total in the Insight tables in the Homey.
But if I look in the app settings the rain sensor is reporting in several decimals (16) than the reported 2.
As I also have had Telldus for a longer time this was reporting the total in mm not m3.

Now to my question.
Is it possible to have any change to mm as total instead of m3 or have the possibility to change it my self in some settings.
Or can you extend the result to 4 decimals then I can see if the total rain is > 1 mm total.

Else the app is great and I having several 433Mhz sensors in the system bot with Homey Pro and Homey Bridge. 

Best regards from Mats in Sweden.

**Comment by nlrb** [comment]
Hi Mats,

I'm using the default Homey capability `meter_rain`, which needs to be reported in m3. See https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html. Athom also defined the amount of decimals (see the json if you click the dots). So this is not something I can change. You could ask Athom, but I doubt they will change this.

Best regards,
-Ramón.
