### ISSUE TITLE
Beta 1.2.2

### ISSUE THREAD

**Issue by g-mannen** [nlrb/com.weather-sensors#15]
Not able to choose temperatur sensors that are listed in Homey under the optins. The checkboxes are not "klickable"
The Sensors are FineOffset under Alecto v3

**Comment by nlrb** [comment]
Can you add some screenshots to explain?

**Comment by g-mannen** [comment]
![sensor](https://user-images.githubusercontent.com/33374258/32856677-c543f6c0-ca45-11e7-80c1-a87866bb4b34.png)
Trying to add them into Homey by klicking the checkbox (black circle)
This is in the full PC Athom client

**Comment by nlrb** [comment]
You cannot add devices in the app settings page. You'll need to go to 'Devices', press the '+', select 'Wireless Weather Sensors' and start the pairing process for the sensor you want to add.
