### ISSUE TITLE
No sensors showing up

### ISSUE THREAD

**Issue by fredrikjohnsson** [nlrb/com.weather-sensors#16]
I have a bunch of temperature sensors with protocol LaCrosse TX3 and WTGR800, but none of them show up under available sensors. WTGR800 is probably not supported, but the other ones should be. 
[stats1510812908856.txt](https://github.com/nlrb/com.weather-sensors/files/1477511/stats1510812908856.txt)

**Comment by nlrb** [comment]
- TX3: I do see data for LaCrosse, but it all shows either CRC or parity errors. Can you try the Athom LaCrosse app to see if that works better?
- WTGR800: this is an Oregon Scientific v3 sensor. However, there is no data for Oregon Scientific v3.

**Comment by fredrikjohnsson** [comment]
I've tried the LaCrosse app now and nothing happens, no sensors found. Maybe I was wrong thinking it is LaCrosse TX3, that is what Domoticz is reporting anyway using RFLink.

**Comment by nlrb** [comment]
Whta sensor is it? Do you have a picture and brand/type number?

**Comment by fredrikjohnsson** [comment]
It looks like this (silver) and on the back it says Viking 02811. I also have a couple of WT450H (white).

![0281102 small -600x600_0](https://user-images.githubusercontent.com/5101886/32908404-c23ef4ca-cb03-11e7-835c-fa835d34e8fe.jpg)
![8873331130398](https://user-images.githubusercontent.com/5101886/32908507-1699d184-cb04-11e7-9f4d-9d2a0e681eb9.jpg)

**Comment by nlrb** [comment]
The Viking 02811 uses the WH3 protocol - would need to look into that. I do notice Alecto v3 receives a lot of data, but is all seen as invalid (as there is no humidity and the temperature is -22.1).

The uses Esic WT450H uses Hideki protocol from what I can find.

**Comment by fredrikjohnsson** [comment]
I actually moved one of each sensors to the same room as the Homey, and then I got values from Eric WT450H. The range has always been a problem with that one, so maybe that was the issue.

Let me know if there is anything I can do to assist you, sending data or whatever. Here is a later version of the dump, with the Esic working.

[stats1510857285251.txt](https://github.com/nlrb/com.weather-sensors/files/1479778/stats1510857285251.txt)

**Comment by rhannink** [comment]
Hello,

Iam on firmware 1.5.6RC3 and since two days, all my sensors are gone and no new sensors are detected anymore........They used to work without any problems laste year. I have Ventus W044 (protocol 1) hum/temp sensors.

**Comment by nlrb** [comment]
@rhannink Maybe you should report this to Athom instead of here. Firmware 1.5.6RC3 is not public. The app has not changed, so I guess they need to look at the firmware. I cannot help you with this.

**Comment by rhannink** [comment]
@nlrb 
Ok thanks, I will do that.

**Comment by rhannink** [comment]
@nlrb

Ramon, a PTP reset did the trick. The sensors show up again.
