### ISSUE TITLE
Alecto WS-1200 sensor not showing up

### ISSUE THREAD

**Issue by epjjansen** [nlrb/com.weather-sensors#18]
Hi I bought a Alecto WS-1200 so I could measure the outside temperature
But in Homey the sensor does not show up
Distance Sensor <-> Homey 10cm.
Homey Firmware Version: 1.5.5

Any suggestions?

**Comment by nlrb** [comment]
Can you download statistics and attach the JSON file here?

**Comment by epjjansen** [comment]
[stats1512389400862.zip](https://github.com/nlrb/com.weather-sensors/files/1526938/stats1512389400862.zip)

**Comment by nlrb** [comment]
There is no signal received at all. How long was the app running? You could try to power off Homey and restart - sometimes that helps to bring the 433Mhz reception back.

**Comment by epjjansen** [comment]
I have Rebooted Homey 2 times
The sensor is laying besides Homey for 48 hours now
Restarted the App 3 times now in the last 48 hours
No result.

**Comment by nlrb** [comment]
Are other 433Mhz apps working (e.g. Klik-Aan-Klik-Uit)?

**Comment by epjjansen** [comment]
they did before, but I have not used them for a while due to a replacement scenemaker
Will let you now this evening

**Comment by epjjansen** [comment]
All other "Klik-Aan-Klik-Uit" devices didn't work either.
Found the solution, a hard reset of homey fixed the 433Mhz receiver. 
I had to unplug the power, wait for 10 seconds and it works now

**Comment by nlrb** [comment]
Good to hear! Do you have another JSON file for me? Then I can use that data in my test scripts. I don't have any WS-1200 data yet.

**Comment by epjjansen** [comment]
[stats1512460760704.zip](https://github.com/nlrb/com.weather-sensors/files/1530843/stats1512460760704.zip)

**Comment by nlrb** [comment]
Thanks!

**Comment by epjjansen** [comment]
I have also a Philips alarmclock with an external sensor. Will try to connect it also. Seems to run on 433Mhz also. Keep you posted

**Comment by nlrb** [comment]
I'm confused now: the data is from a WS-1100, not a WS-1200....

**Comment by epjjansen** [comment]
[stats1512975455671.zip](https://github.com/nlrb/com.weather-sensors/files/1546819/stats1512975455671.zip)
Now with WS-1100 AND WS-1200 stats

**Comment by nlrb** [comment]
All data in this file has CRC errors and is unusable.

**Comment by epjjansen** [comment]
This is what I get from Homey, both sensors are outside. The Rain sensor WS-1200 is still covered in snow. Maybe this causes the errors

**Comment by nlrb** [comment]
Well, only the last 12 readings are stored in the JSON file and the pass/fail ratio of your current readings is 50/50. You can just look at the JSON file with a text editor and see if the last data entries are OK or not.

**Comment by epjjansen** [comment]
I will move the sensor closer to Homey. I will get less rain, but hopefulle a better reading. Keep you posted.

**Comment by epjjansen** [comment]
[stats1513092758311.zip](https://github.com/nlrb/com.weather-sensors/files/1552155/stats1513092758311.zip)

last .json with a better pass/fail ratio

**Comment by nlrb** [comment]
Yes, but unfortunately only data of the WS-1100... For the WS-1200 the length is > 40.

**Comment by epjjansen** [comment]
the new Homey Firmware Version: 1.5.6-rc.6 is just installed. With this version the WS-1200 does not show up anymore.
Will it help if I remove the app and start over?

**Comment by nlrb** [comment]
That is very strange. Re-installing the app won't help with that. The same code is used for receiving the signal of the WS-1100 and the WS-1200.

**Comment by epjjansen** [comment]
More people are complaining about the 1.5.6-rc.6 which causes all the 433 devices to break.

**Comment by nlrb** [comment]
Good to know, but do you have a reference? I don't see an issue on GitHub for it.

**Comment by epjjansen** [comment]
It is on the forum
https://forum.athom.com/discussion/comment/64307/#Comment_64307

**Comment by epjjansen** [comment]
In RC 11 the ws-1200 showed up, but broke again in Homey Firmware Version: 1.5.6

**Comment by nlrb** [comment]
Yes, that makes sense. See https://github.com/athombv/homey/issues/2075#issuecomment-366507352.

**Comment by epjjansen** [comment]
@nlrb Hi Ramón, I would like to donate my WS-1200 Sensor and original display and WS-1100 sensor to you. So you can develop the app for Homey.
I have switched to a zigbee sensor instead. Plz tel me where to send it.

**Comment by nlrb** [comment]
Hi Erwin, that is very kind. I already have the WS-1100 myself and I guess the WS-1200 works the same (as you said it showed up in FW 1.5.6). What I need most right now is Homey FW with properly working 433Mhz reception :-). Grtz R.
