### ISSUE TITLE
Telldus Temp/Hyg Sensors

### ISSUE THREAD

**Issue by NilsLun** [nlrb/com.weather-sensors#19]
I have a number of Telldus sensors that should in theory work but they only display in the Weather app haphazardly. 

When I look at the debug status file, it looks to me that there are multiple CRC issues. see below.

Anyone know what the issue might be?
Unsupported protocol or some kind of interference ?
If it was interference, then I'd suspect the errors to be different and not consistent.
If it's protocol, then why does it occasionally work ?

				"[00:20:37.692] 42 [1,1,0,1,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0]",
				"[00:20:37.693] Error: CRC error (233 vs 130)",
				"[00:21:25.751] 42 [1,1,0,1,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0]",
				"[00:21:25.752] Error: CRC error (233 vs 130)",
				"[00:22:13.692] 42 [1,1,0,1,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0]",
				"[00:22:13.693] Error: CRC error (233 vs 130)",
				"[00:23:01.694] 42 [1,1,0,1,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0]",
				"[00:23:01.695] Error: CRC error (233 vs 130)"
			],
			"last": {
				"id": "135",
				"channel": 1,
				"name": "WH2A",
				"data": {
					"temperature": 25.2,
					"humidity": 46
				},
				"protocol": "alectov3",
				"lastupdate": "2017-12-09T21:55:01.734Z"
			}
		}
	},

**Comment by nlrb** [comment]
Can you attach the full JSON file here?

**Comment by NilsLun** [comment]
Sure, attached
The one ending 32 is from yesterday, where the device is identified as WH2A and the temp and humidity is correct.
The one ending 53 is from just now, it seems to have misunderstood the device in there and identified it as rain meter, which its not.

The correct type is FT007TH (Telldus, which I think is a secondary brand, the real manufacturer is called Proove AB) 
This sensor reports one temp and one humidity value.

I have another similar sensor, F007TPH, which reports two temperatures and a humidity, Have not switched that one on yet.
 
with best regards,
Nils

**Comment by nlrb** [comment]
You are probably using the app from the app store. If you use the latest code from GitHub and install with the CLI it should work OK.

**Comment by NilsLun** [comment]
Thank you, that worked like a charm.
with best regards,
Nils
