### ISSUE TITLE
Temp Sensor Viking Art Nr: 02035

### ISSUE THREAD

**Issue by kivimart** [nlrb/com.weather-sensors#21]
The beta release on viking sensors only goes down to -20 and comes back when it goes over that temp.

**Comment by nlrb** [comment]
Yes, I am aware of that. Do you have a json file with data of temperatures < -20 (download statistics)? If so, please attach it here and I'll see if I can improve it.

**Comment by kivimart** [comment]
Sorry no how do i get json data, can it be done with rftrx USB receiver on windows .?

**Comment by nlrb** [comment]
Go to the Wireless Weather Sensors app settings page in Homey and click on ‘Download statistics’ under ‘Debug’.

**Comment by kivimart** [comment]
Ok here it is, its name is

Alecto v3 | Temperature | 3 | 174 | Thu Dec 21 2017 10:21:24 GMT+0100 (CET) | {"temperature":-19.9} | Temp: Frys

[stats1513890666018.zip](https://github.com/nlrb/com.weather-sensors/files/1580625/stats1513890666018.zip)

**Comment by nlrb** [comment]
Ok, thanks. According to the manual the sensor can measure up to -40. So I'll allow values up to -40.

**Comment by kivimart** [comment]
Installed and i works. perfect tanks

**Comment by kivimart** [comment]
How can i buy u a beer.?

**Comment by nlrb** [comment]
Not needed, thanks ;-).

**Comment by kivimart** [comment]
I could send u one of these and maybe you could get it to work homey.

![sparsnas](https://user-images.githubusercontent.com/34610135/34318045-92aabe84-e7bd-11e7-8b43-10c3e7872165.JPG)

**Comment by kivimart** [comment]
link to the protocol used
https://github.com/strigeus/sparsnas_decoder

**Comment by kivimart** [comment]
ok understood
