### ISSUE TITLE
Same id for all THGR810?

### ISSUE THREAD

**Issue by tregota** [nlrb/com.weather-sensors#22]
Seems only the model-part of the id is used for the id so all my THGR810 measurements end up on the same device. The id is just F824. These are my thermometers:
PROTOCOL            MODEL               ID      TEMP   HUMIDITY
oregon                  F824                    27      21.9°   23%
oregon                  F824                    16      23.2°   21%
oregon                  F824                    10      -0.6°   85%
Makes for a wildy fluctuating and confusing graph in my case.. :)

**Comment by nlrb** [comment]
Yes, you should put them on different channels. There are 10 channels on the THGR810 selectable by dip switches.
