### ISSUE TITLE
Sensor marked inactive

### ISSUE THREAD

**Issue by camilleversteeg** [nlrb/com.weather-sensors#25]
I just bought four Cresta TX320, installed your app ,created devices. All went very smoothly. 

But all devices are marked inactive while they received data less than a few minutes ago. 

![image](https://user-images.githubusercontent.com/15101655/34461728-b7942200-ee32-11e7-9add-51a0607dbe26.png)
![image](https://user-images.githubusercontent.com/15101655/34461729-c162b9d6-ee32-11e7-8ebd-5cfe8102e74c.png)
![image](https://user-images.githubusercontent.com/15101655/34461733-cb3b8596-ee32-11e7-972f-65d95fe3f1f0.png)

I changed the default setting to 1 day. But that didn't help. Maybe i should have a little bit more patience. But its the first time using your app. So there might be an issue.

**Comment by nlrb** [comment]
What is your Homey firmware version?

**Comment by camilleversteeg** [comment]
Homey Firmware Version: 1.5.6-rc.7

**Comment by camilleversteeg** [comment]
I used a Chrome Web browser to add the devices.

**Comment by camilleversteeg** [comment]
![image](https://user-images.githubusercontent.com/15101655/34461858-76f64c88-ee36-11e7-9d9f-a568afd46337.png)

I also noticed that I renamed a few devices and that its not directly shown on the 'Homey device' column. Old names are shown there.

**Comment by camilleversteeg** [comment]
Could it be that the default setting is marking an item as inactive is 5 min. And that the application-settings are applied when it receives it data for the second time.

**Comment by nlrb** [comment]
Have you reloaded the page in Chrome (ctrl-R)? Sometimes availability is not shown correctly in Homey with a web browser.

**Comment by camilleversteeg** [comment]
Yeah refreshed multiple times. But I think I know what happend:
* When adding a device for the very first time, the app setting for going inactive is not taken into account and the device was set inactive within 5-10min. When Homey receives data for the second time, it apply's the app setting and the devices goes active.
* When renaming a device, its renamed in the setting page when data is received for that device.

It is working now properly. It was just confusing when I started.

**Comment by nlrb** [comment]
Last item is indeed as it works for a rename. When a device is added for the first time, the status is set on initialization, but Homey does not always display this properly. That is a Homey bug.

**Comment by camilleversteeg** [comment]
It works wonderfully now btw 👍 thanks for the app
