### ISSUE TITLE
Telldus Thermo/Hygro sensor

### ISSUE THREAD

**Issue by gotthD** [nlrb/com.weather-sensors#30]
Hi, I have three Telldus Thermo/Hygro sensors and they all work from time to time. These sensors seems to utilize the Alecto v3 protocol. The thing is that there seems to be an issue with receiving or decoding the signals from these sensors. If I have the sensors in the same locations and have them connected to my old 433mhz receiver then they are updated frequently (1-10 minutes intervall), after connecting them to Homey and using your plugin one of the devices are updated at max once every day and the other two (5-60 minutes).

Can there be an issue with the error control or do you think it is the 433 receiver in the Homey that is the issue?
[stats1520431195172.txt](https://github.com/nlrb/com.weather-sensors/files/1789362/stats1520431195172.txt)

Thanks for your good work.

**Comment by nlrb** [comment]
Are you happening to use firmware 1.5.6 or 1.5.7? If so, it is likely related to https://github.com/athombv/homey/issues/2075.

**Comment by gotthD** [comment]
Checked and found Firmware Version: 1.5.3

**Comment by nlrb** [comment]
As Athom is rewriting the core of the 433 stack, I prefer to wait for that before digging deeper. That might well fix your issue.

**Comment by WeylandYutaniCorp** [comment]
I have a Telldus Thermo/Hygro 433 for inside Temp Hygro/Outside Temp that only shows inside temp. It's a Alecto v3 and Identify itself as WH2 in Homey, but only one value out of three is registrered. 
https://telldus.com/produkt/in-and-outdoor-thermo-hygro-sensor-433mhz/

**Comment by nlrb** [comment]
@WeylandYutaniCorp I don't have that sensor and they don't ship to NL. Can you make a recording of the signal (https://developer.athom.com/tools/signals)?
