### ISSUE TITLE
Tfa support

### ISSUE THREAD

**Issue by kallewahlback** [nlrb/com.weather-sensors#37]
Hey, I have multiple TFA sensors, mainly the 30.3302.02 (http://tfa-dostmann.de/fileadmin/-----Anleitungen-----/30.3302.02_g_e.pdf). They are great sensors but the weather sensors app/homey is not able to find them. It would be great if some kind soul could make implement them in the app. I could send one to the developer if needed,

Thanks!

**Comment by nlrb** [comment]
The 868MHz FSK signals cannot be received by Homey.
