### ISSUE TITLE
Could you add support voor alecto ws-1150

### ISSUE THREAD

**Issue by basd82** [nlrb/com.weather-sensors#38]
Could you add support voor alecto ws-1150

**Comment by basd82** [comment]
in the debug file i see it recieves trafic the homey but marks it invalid
[stats1527190498400.json.txt](https://github.com/nlrb/com.weather-sensors/files/2036860/stats1527190498400.json.txt)

**Comment by nlrb** [comment]
I'll look into it as soon as Athom has solved https://github.com/athombv/homey/issues/2075.

**Comment by nlrb** [comment]
Can you check with the latest version of the app to see if it works? And if not attach new readings?

**Comment by basd82** [comment]
Its not working.But download stats button is not working in homey 2.0 the app craches
Met vriendelijke groet,
Bas van den Dikkenberg
Op 26 jan. 2019 19:42 schreef Ramón Baas <notifications@github.com>:


Can you check with the latest version of the app to see if it works? And if not attach new readings?

**Comment by nlrb** [comment]
Sorry for the long wait, but could this have been the data values at that time?
```
 { id: '207',
  name: 'WS-1150',
  channel: 3,
  data: { temperature: 24.1, button: false, lowbattery: true } }
{ id: '207',
  name: 'WS-1050',
  channel: 3,
  data: { temperature: 23.9, button: false, lowbattery: true } }
```
Does the temperature match and was the battery low?
