### ISSUE TITLE
Support for Oregon Scientific WGR800 Wind sensor

### ISSUE THREAD

**Issue by solpojke** [nlrb/com.weather-sensors#39]
I have downloaded the app and I have a brand new Oregon Scientific WGR800 Wind sensor, protocol 3, which doesn't show in the list of supported devices. 

(I can't find any other of my 433 MHz temp/humidity sensors either... all of them working in my old Telldus system and from various suppliers/brands (Some Telldus))

Is there something I have missed or is it something wrong with the setup of my Homey or is it the app?

**Comment by Lansuper** [comment]
This goes for me too. The json download gives errors on unknown ID's. (1a8a, 415f, 2ae1, a8af, 54d7, 2415).  ID f824 is the only one working (6% of the total number of communication attempts)

**Comment by nlrb** [comment]
Caused by athombv/homey#2075. Needs a Homey firmware fix.
