### ISSUE TITLE
UV value is not displayed

### ISSUE THREAD

**Issue by nlrb** [nlrb/com.weather-sensors#4]
I have the Oregon UV sensor model UVN800 connected (Oregon Scientific v3 protocol). Unfortunately only its battery status is available in Homey. The analoge value and/or UV-index are not visible.

**Comment by Washburned** [comment]
Hi, I see you have created the issue yourself. 
Can I drop here the debug files / loggin info?

**Comment by nlrb** [comment]
Good to hear. I think I've found the issue. Can you download statistics and attach the json file here?

**Comment by Washburned** [comment]
Had to zip it, as a   .json  extension cannot be attached.
 
[stats1496346975136.zip](https://github.com/nlrb/com.weather-sensors/files/1045902/stats1496346975136.zip)

**Comment by nlrb** [comment]
Can you check the latest version and see if the issue is fixed?

**Comment by Washburned** [comment]
The latest version (v1.1.1) is not in the app store yet. Or is there a other way to pre-check it?

**Comment by nlrb** [comment]
Yes, you can side-load the github code with the athom cli.

**Comment by Washburned** [comment]
Oke, that took a while to figure that out. I have side-loaded v1.1.1, but unfortunately I don't see any changes.

**Comment by nlrb** [comment]
Could you add a screenshot of the device card & the app settings page? Could you also delete the device and re-pair?

**Comment by Washburned** [comment]
Yes, but that will be end of the afternoon.

**Comment by Washburned** [comment]
Deleted UVN800 on the Device page and Added (re-paired) again.

![schermafdruk 2017-06-02 16 57 01](https://cloud.githubusercontent.com/assets/29127831/26732038/7e3d22ea-47b6-11e7-92c9-f38dc2ab0b28.png)
![schermafdruk 2017-06-02 17 00 43](https://cloud.githubusercontent.com/assets/29127831/26732040/7e3fad3a-47b6-11e7-9ae9-2cfc1dbceaa8.png)
![schermafdruk 2017-06-02 17 01 43](https://cloud.githubusercontent.com/assets/29127831/26732039/7e3e44fe-47b6-11e7-8fce-5b85330c47a6.png)
![schermafdruk 2017-06-02 17 01 53](https://cloud.githubusercontent.com/assets/29127831/26732041/7e3ff510-47b6-11e7-9dcb-331a7e15ca44.png)
![schermafdruk 2017-06-02 17 02 26](https://cloud.githubusercontent.com/assets/29127831/26732043/7e4dce1a-47b6-11e7-839e-981f8e76cd18.png)
![schermafdruk 2017-06-02 17 03 17](https://cloud.githubusercontent.com/assets/29127831/26732042/7e450870-47b6-11e7-87ff-9ac247d530f4.png)

**Comment by nlrb** [comment]
Thanks, good to see it all works now!

**Comment by Washburned** [comment]
Allmost. For the flowcard only the battery status is available. There is no card for the UV-index itself (is the most important card/value).  See the fourth screen. The mouse pointer is not displayed, but it is hovering over the card in the And-column. It shows only the cross beside the card to delete it, but no up/down arrows to select the card with the UV-index.

**Comment by nlrb** [comment]
This is a default capability, so Athom should provide such a card.

**Comment by Washburned** [comment]
Oke, so I have to bring this issue to the Athom forum.
Thanks for your support sofar.
