### ISSUE TITLE
Alecto WS-1200

### ISSUE THREAD

**Issue by hansjeover** [nlrb/com.weather-sensors#41]
Alecto WS-1200 doesn't appear anymore in the found sensors, the weather station is placed nearby the homey (approx 5 cm). The outdoor sensor ( temp and rain) are displayed on the Alecto station.

is there a special way of "connecting" to the homey or is this the result of a software upgrade.

Regards Hans

**Comment by nlrb** [comment]
Expect this to be related to 
https://github.com/athombv/homey/issues/2075

**Comment by hansjeover** [comment]
Yeh, maybe it is. I'm more interested in a solution.

**Comment by nlrb** [comment]
Does it work with the latest version of the app & Homey FW?
