### ISSUE TITLE
30.3168 Solar Windmeter TFA, not found

### ISSUE THREAD

**Issue by Handyman4u** [nlrb/com.weather-sensors#44]
Hi,

my solar windmeter doesn't seems to be found.

My tempsensor is ok en found!

I do see something in the downloaded data.

Can u check and see what is going on?

Thanks & regards,

Hans
[stats1543320440314.txt](https://github.com/nlrb/com.weather-sensors/files/2635993/stats1543320440314.txt)

**Comment by nlrb** [comment]
There is not a lot of data in the log file. Do you have one with more data? From what I read [here](https://github.com/RFD-FHEM/RFFHEM/issues/129) it might me that the message for this wind meter is longer. Can you capture the signal in a recording (https://developer.athom.com/tools/signals)?

**Comment by Handyman4u** [comment]
Hi, well problem is that my wind solar is on the roof and the capture of 433 is only for a second of 3, 
the pulse of my solar is around every 40 sec, but unable to capture. could also be that the distance is to long, i might take it off the roof, but will only do this if the weather is good.

**Comment by nlrb** [comment]
Probably easier to take Homey closer with a power bank.

**Comment by Handyman4u** [comment]
yes true but i can push a button on the solar which send out the signal, now i am just aming for this signal to be recieved by homey

**Comment by nljvd** [comment]
Hi ,
Thanks for the app, the windmeter is working!
But the temperature is not. When i check the device in configure app the raw data says the temperature is 20 degrees. 
But when i check the temperature in device at the devices section in homey the temperature is unknown.

Regards Joshua

**Comment by Handyman4u** [comment]
Hi,

yes since last Homey Update my Windmeter is also found and working now!,
I don't undestand the Temperature fuction since this is not implemented in the windmeter?
My point of vieuw just needs to be removed but glad wind is working now!

**Comment by nlrb** [comment]
Which protocol was this again?

**Comment by nljvd** [comment]
Hi 
The protocol is cresta/tfa.

**Comment by Handyman4u** [comment]
HI,
is it possible to get an diffrent value for the wind direction? at the moment it is showing degrees, but i want this to show the direction like N

**Comment by nlrb** [comment]
You would need to ask Athom. The app uses the default `wind_direction` capability, which is in degrees. See https://developer.athom.com/docs/apps-reference.

**Comment by nlrb** [comment]
Do you happen to have a data stream from the app I can use? I.e. a 1,0,1,1,0,... when you run the app via CLI with `athom app run`? The protocol always expects a temperature measurement to be part of the wind meter data.
