### ISSUE TITLE
THGR810

### ISSUE THREAD

**Issue by HampusHaak** [nlrb/com.weather-sensors#46]
After updating to Homey 2.0 
THGR810 is not connected and cant find it.

After adding, it works for like 1-2 min after that it says
Device is unavailable
No sensor datat received since Thu Dec 06 2018
And the time.

**Comment by nlrb** [comment]
Please take that up with Athom. I guess they broke something again then.

**Comment by HampusHaak** [comment]
I have done that, they say i should write to you.

**Comment by nlrb** [comment]
That doesn’t make sense. The app has not changed, the FW has. I don’t even have tha FW to reproduce. Please open a case with Athom.

**Comment by Lansuper** [comment]
Could you please look into this yourself? The firmware has indeed changed and this was advertised by Athom for some time now with the urgent request to the developers to make the necessary changes. 
Now the flows with the weather sensors in it don’t work and some crucial flows depend upon it. I know v 2 is experimental, but for me it’s the only app not working.
Your help is much appreciated!

**Comment by HampusHaak** [comment]
Athom - General (Athom)

Dec 14, 19:28 CET

The developer should report the issue to us, we will then look into it!

— Athom Support

**Comment by nlrb** [comment]
Should be fixed with version 2.0.0.
