### ISSUE TITLE
Release a new version to Athom Apps?

### ISSUE THREAD

**Issue by dfuchslin** [nlrb/com.weather-sensors#48]
I've been using your app for > 1 year now, thank you for you hard work!

According to the Athom/Homey Apps, the latest version of your excellent app is v1.2.1 - 07.08.17 (https://apps.athom.com/app/com.weather-sensors). According to the commit log in github there have been quite a few commits after 7 August 2017 and yet no new version is available via Athom. I have manually installed the latest from github directly to my Homey (firmware 1.5.13) and notice an incredible difference in reliability: no more timeouts of sensors, sensor reporting seems faster and more reliable. Perhaps submitting a new official version to Athom (with all the latest commits) will also fix problems others are facing with the new Homey 2.0 firmware?

Thank you!

( I notice this may be a duplicate of issue #34 )

**Comment by nlrb** [comment]
@dfuchslin Glad to hear you've been using the app to good effect. Unfortunately Athom has been changing the firmware regarding 433 Mhz signal reception. That has broken mainly this app - as there are several signals types that it (could) receive. There are unfortunately still to many issues with the Homey FW that make that the signals it could receive before, it cannot receive anymore. For some reception has improved , for others it is completely broken. Hence I have not released a new version of the app. For some users that would be step forward, for others it would be a step backwards.

**Comment by dfuchslin** [comment]
Ok, I see--frustrating situation! We appreciate the work you do on this app; if there is anything we your users can do to help out please let us know.

For the record, I have only sensor types "Auriol" and "Cresta/TFA" enabled and now have zero/few problems with the 1.5.13 firmware (whereas before I manually installed your latest from github I would get multiple connection problems/inactive sensor daily).

**Comment by johane77** [comment]
This has been One of My favourite apps, except controlling lights. Any possibility a new release ever will happen?

**Comment by MennoDIJKSTRA** [comment]
Hay David, can you tel me how i manually update the app trough Github?
I have got TFA weathersensors but they won't show up.... :-(

thanks in advance 

Menno

**Comment by dfuchslin** [comment]
Hi @MennoDIJKSTRA, follow the instructions over at Athom to install the developer tools: https://developer.athom.com/docs/apps/tutorial-Getting%20Started.html (i.e. install nodejs on your machine then install the athom dev tools). Then clone this github repository to your local machine, go into the directory, and then run `athom dev install`.

**Comment by nlrb** [comment]
New version (2.0.0) has been submitted, awaiting approval.

**Comment by nlrb** [comment]
Now available in the store.

**Comment by dfuchslin** [comment]
Awesome, thank you @nlrb!
