### ISSUE TITLE
Inactive time not working properly on v2

### ISSUE THREAD

**Issue by Lansuper** [nlrb/com.weather-sensors#49]
Thanks for releasing the v2 app. Although I have the timeout for my Oregon devices on 5 hours, they timeout within half an hour and therefore switch to unavailable regularly.

**Comment by nlrb** [comment]
Thanks for reporting. This will only happen if you have never updated (saved) the app settings. Quick fix would be to save the app settings.

BTW: if you get such infrequent updates of Oregon sensors, it might help to replace batteries (no guarantee though). Although the batteries might not be empty, it will help Homey if a stronger signal is sent.
