### ISSUE TITLE
App stopps working... 

### ISSUE THREAD

**Issue by Pinnacle74** [nlrb/com.weather-sensors#50]
I'm having issues with the latest update (2.0.0), the app stopps working.

This is the number I got when I created a diagnostic report in the app 5095c3f9-a271-4c45-a763-ab604a46f971

**Comment by nlrb** [comment]
Thanks for reporting. I've fixed the typo in the GitHub repo and it will be in the next release. In the meantime, as a workaround, disable notifications in the app when a signal becomes available again.
