### ISSUE TITLE
Getting error message when adding new sensor

### ISSUE THREAD

**Issue by Pinnacle74** [nlrb/com.weather-sensors#51]
![screenshot_20181231-090020_homey gen 2](https://user-images.githubusercontent.com/36757347/50556904-87f91880-0cdf-11e9-9078-0a4624528c34.jpg)

The app is able to find two of my sensors but I get an error message when I try to add them as a new device.

**Comment by Pinnacle74** [comment]
![screenshot_20181231-093831_homey gen 2](https://user-images.githubusercontent.com/36757347/50556931-e6be9200-0cdf-11e9-8757-a5a788e69f26.jpg)

**Comment by nlrb** [comment]
Thanks. This is specific for the UPM/Esic signal. Will be fixed in the next release.

BTW: 
a) FW 1.5.13 handles this more gracefully.
b) From you screenshot it looks you cannot select protocols from the app settings

**Comment by Pinnacle74** [comment]
You are correct, I'm not able to select protocols from the app settings but I was planning to submit this as a separate bug a bit later... 🙂

**Comment by nlrb** [comment]
Propose you submit this with Athom - it works fine if you don't use the app.
