### ISSUE TITLE
Unable to add temperature/humidity-sensor

### ISSUE THREAD

**Issue by StefanO-Kjell** [nlrb/com.weather-sensors#52]
On latest version v.2.0.1 I'm unable to add a temperature/humidity-senso. It just says "Invalid setting type! Got number but expected string (label) for id.

Any idea?

**Comment by nlrb** [comment]
Duplicate of #51.

**Comment by StefanO-Kjell** [comment]
Sorry, only checked the open issues 🙈

**Comment by nlrb** [comment]
No problem, will include the fix in the next release.
