### ISSUE TITLE
Some problems with new SDKv2 app

### ISSUE THREAD

**Issue by rhannink** [nlrb/com.weather-sensors#53]
I am using 2.0.2 on Homey 2.0-RC11 and I have found some issues:

I have two hum/temp sensors Ventus W044, only one is detected
I cannot chaos the different protocols from the settings page (alecto V1, V2 ect)

Keep up the good work......

**Comment by nlrb** [comment]
For the Ventus sensors, it is impossible for me to debug, especially wihout logging.
The protocol selection on the app is an issue for Athom. It works fine on FW 1.5.13 and a browser. I cannot debug it with the new app, as I don’t have that.

**Comment by rhannink** [comment]
I am now at 2.0-RC14 firmware and the app also detected my second temp/hum sensor....
But both sensors generate a lot of "Sensor <b>Woonkamer</b> is inactief" messages. They did not do this with the RC11 firmware.
Can I get the logs for you from my system ?

**Comment by nlrb** [comment]
You can turn off the inactivity notifications in the app settings or increase the time before they are marked inactive.

**Comment by rhannink** [comment]
Check......I turned off inactivity notification. They probably went off because some of the messages are corrupted as can be expected by this 433Mhz unidirectional protocol.

Everything seems fine now......

**Comment by WollyA** [comment]
I have the same issue as @rhannink... In the 2.0 app it is not possible to select protocols. A selection box pops up for a short while with something like {{item.name}}. It looks like something in settings/index.html. Can it be something with margins and paddings when using a <legend> tag in another <legend> tag? I can see the 433Mhz legend, but it is very small and there is nothing in it. Can you please take a look at it? That would be great.

**Comment by nlrb** [comment]
Difficulty is that this only happens in the 2.0 app. Since I am not running the 2.0 firmware, I cannot reproduce it myself.

**Comment by WollyA** [comment]
I know. Everything was running fine before. I looked into your html code and this seams to be fine. It breaks as soon as Homey starts to fill the {{item.name}} part dynamically.

I will try to download your source code and install it through CLI to play around as soon as I find the time. I hope you’re fine with this? I’m no code guru, but I’m stubborn as a mule and this doesn’t look like a big thing.

**Comment by pjmpessers** [comment]
433mhz protocols is visible again with v2.0.3 that can be downloaded on github and sideloaded with node.js.

**Comment by pjmpessers** [comment]
I don't know when he is planning to release it. I sideloaded it.

**Comment by nlrb** [comment]
@pjmpessers You tried out this change (see #47) and according to you the settings were still not visible. Hence I have not pushed this version to the app store. So you are now saying this change does resolve it?

**Comment by pjmpessers** [comment]
Sorry for the confusion. I didn't know i was telling that v2.0.3 didn't solve the protocol problem, because it did. V2.0.2 has the protocol problem. But it is solved in v2.0.3. Sorry if i made a mistake.

**Comment by nlrb** [comment]
Submitted v2.0.3 to the app store for approval.

**Comment by WollyA** [comment]
I installed the update 2.0.3. Problem solved with the 433Mhz protocol. Great!
