### ISSUE TITLE
Value on sensors in the application 

### ISSUE THREAD

**Issue by onne1951** [nlrb/com.weather-sensors#55]
Please insert values in the apps, so that you do not have to klick on every sensor to get the value

**Comment by nlrb** [comment]
No idea what you are talking about. The app is using the default Homey mechanism. Maybe you can add a screenshot to clarify.

**Comment by onne1951** [comment]
The left one is Thermo-Floor / Heatit that have the temperature reading of
8 degrees, I would love to have that in your app also 😃

Den tors 17 jan. 2019 18:54 skrev Ramón Baas <notifications@github.com>:

**Comment by nlrb** [comment]
I don’t see any image. Can you add that?

**Comment by onne1951** [comment]
I Included the screenshot below

Den tors 17 jan. 2019 19:02 skrev Ove Nilsson <onne1951@gmail.com>:

**Comment by onne1951** [comment]
You can see the screenshot in the link below

https://photos.app.goo.gl/EBQRHt83HgrmUxXc7

Den tors 17 jan. 2019 19:48 skrev Ramón Baas <notifications@github.com>:

**Comment by onne1951** [comment]
https://photos.app.goo.gl/ihUjWJ6dv1MH6m486

Please have the reading and the date/time of the readings on the first tile

Best regards
Ove Nilsson

Den tors 17 jan. 2019 20:01 skrev Ove Nilsson <onne1951@gmail.com>:

**Comment by Pinnacle74** [comment]
This would indeed be highly appreciated and useful to have. :)

**Comment by nlrb** [comment]
Looks interesting. Apparently the UI for v2 needs to be specified differently (sigh). Once I upgrade my Homey to v2 I'll have a look at this.

**Comment by Polsemaker** [comment]
Nlrb, this feature would be much appreciated! Have you been able to look into this?

BR Petter

**Comment by nlrb** [comment]
Nope, still on 1.5.13.

**Comment by nlrb** [comment]
I don't see an option to add this. Looks like Athom only implemented this for thermostat devices to show the setpoint.
