### ISSUE TITLE
WT450h/Esic

### ISSUE THREAD

**Issue by runesyd** [nlrb/com.weather-sensors#58]
Hi,
Thanks for the nice app!
I’m running v2.0.3 and I have successfully added a WT450h/Esic sensor. I have two other identical sensors which I’m not able to add. I only receive the message: «No new devices have been found» when I try to add them. I have disabled all the other «brands» in the setting of the app. Do you knoe what is wrong? Please tell me if you want me to run debugmode.

**Comment by nlrb** [comment]
If you can add some, then the protocol is decoded OK. Are all the sensors on a different channel? Can you attach a debug log (from app settings->download statistics)?

**Comment by runesyd** [comment]
Hi Ramòn,

I'm trying to push the download statistics button (in configure app),
but nothing happens. What is it supposed to do? I can however push the
create diagnostics report (behind the gear wheel button in the app
settings) and get the code from that, but I guess it's not that what you
want?

The code I get is this: ca2c8b04-8709-4cc4-a01d-4df1d5f73e89

I've tried different House Code's and/or channels on the sensors I don't
find. I have a total of 5 sensors (all UPM/esic), and I see 3 of them.
The last 2 ones Homey can't find.

Regards,
Rune

**Comment by nlrb** [comment]
The button only works via a web browser. So if you are using the new app, then there is no way to get that data unfortunately.

**Comment by runesyd** [comment]
Hi again,

Thanks for the quick response!
The web gui is not accessible with Homey 2.0 (firmware), so if you are planning to fully support the new firmware this is probably something you need to address at some point?

Thanks agains. Please let me know if there is something I can do to help. 👍🏼

Regards,
Rune

Sendt fra min iPhone

3. feb. 2019 kl. 12:22 skrev Ramón Baas <notifications@github.com<mailto:notifications@github.com>>:


The button only works via a web browser. So if you are using the new app, then there is no way to get that data unfortunately.

**Comment by gorper** [comment]
May I contribute with a story. I had a for many years working tellstick duo based system including 4 WT450h sensors branded UPM and esic. All of them stated in  system as using Mandolyn protocol. Now I want to rebuild with homey pro as base. None of my proven working WT450h is found by homey and this app. What may be wrong ?

**Comment by nlrb** [comment]
I don't have the sensor myself, so I cannot test/debug it. According to #16, the sensor (did?) work before.

**Comment by gorper** [comment]
Thanks for responding. Yes I saw the #16 and I can figure out why the name Mandolyn protocol is present in my old tellstick duo based system raw data page of discovered sensors. That seems to be a company name. W.H Mandolyn international LTD at least that is on a sticker on one of my UPM branded WT450H. To clarify all my 3pc WT450H and 1 pc WT450 is working with my old system and with original weather station but not in Homey. What can I as truly newbie do to contribute to improvement of this sensor ?

**Comment by nlrb** [comment]
Well, if you have an RTL SDR receiver and can capture the signal, or see if it is recognized by the rtl_433 library, we have something to go on.

**Comment by gorper** [comment]
Thanks a lot for pointing me in a good way. I managed to set up a RTL receiver with a old dvb-t usb interface and did some interesting listening. It gives that my working WT450H( yes suddenly 1 started to work) is sending at 433.850 MHz and those not working with homey is lower in frequency 433.700 and 433.600. For reference i have some nexa remotes they send at 433.904 and 433.914 MHz.

**Comment by nlrb** [comment]
From https://apps.developer.athom.com/tutorial-Signals.html:
> To ensure that Homey is able to listen to these deviating frequencies, it's receiving frequency band has been broadened by 325Khz. This results to a frequency band ranging from 433.76MHz to 434.08MHz for 433 MHz signals

So, yes, 433.700 and 433.600 are out of range.
