### ISSUE TITLE
Cresta temperature/humidity conection

### ISSUE THREAD

**Issue by hunter707** [nlrb/com.weather-sensors#59]
Hi, I'm using sinds the beginning of Homey three cresta temperature/humidity sensors without any problem. Sinds Homey V2 i have connection problems. I changed all the batteries but it doesn't help. It seems to be a range problem. When I put the sensors in a distance of a few meters they will do it. I hope you can fix the problem because I like the app very much.

Thank You,

Hunter

**Comment by nlrb** [comment]
Unfortunately I cannot fix anything regarding range. You might want to raise this with Athom.
