### ISSUE TITLE
Oregon BTHR918N not seen by Homey

### ISSUE THREAD

**Issue by Geert10** [nlrb/com.weather-sensors#6]

**Comment by nlrb** [comment]
Can you download statistics and attach the json file here?

**Comment by Geert10** [comment]
[stats1498715348080.txt](https://github.com/nlrb/com.weather-sensors/files/1111201/stats1498715348080.txt)
[stats1498721280790.txt](https://github.com/nlrb/com.weather-sensors/files/1111200/stats1498721280790.txt)

**Comment by nlrb** [comment]
Are these values correct for the measurements at that time?

temperature: 24.3,
humidity: 52,
comfort: 'Comfortable',
pressure: 874,
forecast: 'Rainy',
lowbattery: false

**Comment by Geert10** [comment]
I am not  home at the moment.  I think that it is correct 


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: nlrb <notifications@github.com> 
Datum: 29/06/17  10:32  (GMT+01:00) 
Aan: "nlrb/com.weather-sensors" <com.weather-sensors@noreply.github.com> 
Cc: Geert10 <g.cnudde@telenet.be>, State change <state_change@noreply.github.com> 
Onderwerp: Re: [nlrb/com.weather-sensors] Oregon BTHR918N not seen by Homey (#6) 

Are these values correct for the measurements at that time?
temperature: 24.3,

humidity: 52,

comfort: 'Comfortable',

pressure: 874,

forecast: 'Rainy',

lowbattery: false

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nlrb/com.weather-sensors","title":"nlrb/com.weather-sensors","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nlrb/com.weather-sensors"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nlrb in #6: Are these values correct for the measurements at that time?\r\n\r\ntemperature: 24.3,\r\nhumidity: 52,\r\ncomfort: 'Comfortable',\r\npressure: 874,\r\nforecast: 'Rainy',\r\nlowbattery: false"}],"action":{"name":"View Issue","url":"https://github.com/nlrb/com.weather-sensors/issues/6#issuecomment-311899499"}}}

**Comment by nlrb** [comment]
The one I am not sure about is pressure. If you can check when you are back home? Check the value on the display and send the json from that time incl. observed value.

**Comment by Geert10** [comment]
reading at 17:21
temperature: 24.6,
 humidity: 46,
 comfort: 'Comfortable',
 pressure: 1002,
 forecast: Licht bewolkt
[stats1498749563807.txt](https://github.com/nlrb/com.weather-sensors/files/1112564/stats1498749563807.txt)
,
 lowbattery: false

**Comment by nlrb** [comment]
Thanks, but unfortunately I can only see the last 5 readings in the log and there is none with ID 5d60 in there. Can you try again. Note that '5d60' has to be there in the json file for a valid reading.

**Comment by Geert10** [comment]
7u48 after reset
[stats1498801531623.txt](https://github.com/nlrb/com.weather-sensors/files/1114241/stats1498801531623.txt)

temperature: 22.6,
humidity: 49,
comfort: 'Comfortable',
pressure: 1006,
forecast: 'sun',
lowbattery: false

**Comment by nlrb** [comment]
Thanks for the data, that is really useful! Issue is now fixed in the latest version of the code. You can either 'side-load' the code via the CLI, or wait ~1 week for it to become available in the app store.

**Comment by Geert10** [comment]
I have also other sensors on my weather station , are they suported ?
Anemometer (WGR918N) ; Thermo – Hygro outside (THGR918N) ; Rain gauge (PCR918N)

**Comment by nlrb** [comment]
1. WGR918N: currently not supported (don't know the id & data layout, is this ID 3a0d?)
2. THGR918N: currently not supported (don't know the id & data layout, is this ID 1a3d?)
3. PCR918N: : currently not supported (don't know the id & data layout)

We could try to add decoding the same way, but please create a separate issue for each device.

**Comment by Geert10** [comment]
i try to isolate the sensors and start a new issue (back on 17/07/2017)
