### ISSUE TITLE
Missing data in insights from wt450h temp/hyg sensors

### ISSUE THREAD

**Issue by runesyd** [nlrb/com.weather-sensors#63]
I’m running v2.0.4 and I have some WT450h/Esic sensors.
None of them is reporting values to insights (https://insights.homey.app/)

**Comment by nlrb** [comment]
Are you seeing the data on the mobile cards and just not in insights? If so, this looks more related to the Homey FW. The app does nothing with insights.

**Comment by runesyd** [comment]
Hi Ramon,

On 08/03/2019 17.50, Ramón Baas wrote:
> Are you seeing the data on the mobile cards and just not in insights? If so, this looks more related to the Homey FW. The app does nothing with insights.
>

It depends on what you mean by mobile cards? I have the same issue as
this, that I only see the values when I click on each device to see
details. The values are not visible on the icon for each device where
you can see all the devices together:
https://github.com/nlrb/com.weather-sensors/issues/55

I have also been in touch with Homey as I'm missing data in insights
from other devices as well, and thought that this was a Homey fw issue.
This issue is the same problem that the data is not coming into insights:
https://github.com/TedTolboom/no.ThermoFloor/issues/13
I sent this issue (missing data in insights from thermofloor) to Homey
first, and this is the answer I got: "I just had contact with the
community developer who developed the HeatIt app and he is aware of an
issue with loading in the Insights for specific HeatIt modules."
This tells me that each app is doing something to send data to insights,
but I might have understood this wrong?

Regards,
Rune

**Comment by nlrb** [comment]
Well, Athom breaks backwards compatibility and then expects all developers to fix their apps. That is not how it works. I don't have a Homey running on FW 2.0.x, so I cannot even this this.

**Comment by nlrb** [comment]
Please try with app version 2.5.0.
