### ISSUE TITLE
Possibility to replace device

### ISSUE THREAD

**Issue by fredrikjohnsson** [nlrb/com.weather-sensors#64]
I would like to have the possibility to replace a device. When I do a battery change on for example a temperature sensor, it will get a new ID and a new device needs to be created and the old one deleted.

**Comment by nlrb** [comment]
Yes, that would be nice. But unfortunately Homey does not support replacing devices. And often the unique ID of a sensor changes with a battery change. That unique ID is needed to identify the sensor in Homey as well. That is why you normally also need to add it to a weather station again in that case.
