### ISSUE TITLE
Auriol devices not found

### ISSUE THREAD

**Issue by cactusss** [nlrb/com.weather-sensors#66]
Hi,

I have an Homey 1.5.13 with the v2.0.3 that find Auriol devices. My new HomeyPro running the latest 2.x firmware however only seems to find Alecto devices, the Auriol isn't found. The two Homeys are setup next to eachother for a range issue is doubtable. What to do?

Thank in advance, kind regards,

Ricardo

**Comment by nlrb** [comment]
Please try with app version 2.5.0.
