### ISSUE TITLE
Oregon PCR800 presents data in wrong format

### ISSUE THREAD

**Issue by lgorroe** [nlrb/com.weather-sensors#67]
The Oregon PCR800 (code 2914) sends rain rate ("rainrate") in inches per hour and total rain ("raintotal") in inches. The data from the PCR800 is however presented in Homey without any data conversion as "Rain" in mm and "Rain Meter"  in m3.  It would be preferable to have a user selection of inches or mm in the device settings, the rain rate presented in mm per hour or inches per hour, and the total rain presented in mm or inches, depending on the user setting.

**Comment by nlrb** [comment]
You are right! For 2914 it should be converted. Regarding unit selection, you would have to ask Athom. The default capability `measure_rain` requires the value to be in mm.

**Comment by lgorroe** [comment]
I would be perfectly fine with a conversion to mm and mm/h :)

Is the presentation as "mm" instead of "mm/h" and "m3" instead of "mm" an Athom issue or an app issue?

**Comment by nlrb** [comment]
All the app does is report the value. The unit text/presentation is done by Homey FW.

**Comment by nlrb** [comment]
Instead of dividing rain total by 1000, I will now divide it by 39.37 (and rain rate 3.937).

**Comment by nlrb** [comment]
Fixed in 2.5.0.
