### ISSUE TITLE
Add support for Alecto WS1700

### ISSUE THREAD

**Issue by HenkeGoransson** [nlrb/com.weather-sensors#69]
Could you please add support for Alecto WS1700?
The protocol is here: https://manual.pilight.org/protocols/433.92/weather/alecto_ws1700.html

**Comment by nlrb** [comment]
Yes, I will incorporate it in 2.5.1.

And you should change the battery ;-)

```
{ id: '38',
  name: 'WS-1xxx',
  channel: 1,
  data:
   { temperature: 9, button: false, lowbattery: true, humidity: 85 } }
```

**Comment by nlrb** [comment]
You can test it via https://homey.app/nl-nl/app/com.weather-sensors/Draadloze-Weersensoren/test/
