### ISSUE TITLE
Oregon BTHGN129 (Thermo/Hygro/Baro Sensor) is not regognized

### ISSUE THREAD

**Issue by petervandervoort** [nlrb/com.weather-sensors#7]
Dear Rámon,
I'm using 'Draadloze Weersensoren' v1.1.2 and try to connect an Oregon BTHGN129 sensor.
I've reset and activated the sensor and left it close to Homey for two days.
In the App I've activated Oregon Scientific v2 and v3 but so far the sensor is not recognized by the app.
Do you know if this sensor is not compatible at all or if the app might recognize it in future?
Or maybe I'm doing something wrong myself :-)
Thanks & Regards,
Peter.

[stats1499168998328.zip](https://github.com/nlrb/com.weather-sensors/files/1121951/stats1499168998328.zip)

**Comment by nlrb** [comment]
Hi Peter,

The BTHGN129 is indeed not supported (yet). I don't know the layout of the data. From what I can find it is a version 2.2 sensor. The ID should be 5d53 (see http://www.osengr.org/WxShield/Downloads/Weather-Sensor-RF-Protocols.pdf). In your received data I find IDs fa5d, 57d4, a5d5, aea9 and 5156 - but not 5d53.

If you can get me a data sample with ID 5d53 I can see if I can find the correct layout and add support.

Best regards,
-Ramón

**Comment by nlrb** [comment]
BTW: later in the spec they refer to '5d35', so also watch out for that one.

**Comment by nlrb** [comment]
And if you have other Oregon Scientific sensors as well, please let me know too.

**Comment by petervandervoort** [comment]
Hi Ramón,
Thanks for your reply.
The BTHGN129 is the only Oregon product I have at the moment.
In fact, I was looking for a weather sensor for Homey and since the BTHGN129 has 3 sensors in one device I ordered it even though I wasn't sure it would be supported.
So I'm very pleased to read that you are willing to adjust the app for the BTHGN129!
I will do my best to find a way to collect a sample of the data it is sending. (not sure yet how to do that though)
When I have that I'll send it to you.

Best Regards,
Peter

**Comment by nlrb** [comment]
Some bad news I'm afraid. Somehow Homey has troubles receiving the signal from the BTHGN129. I only get like 1 correct reading in 2 days. Not sure what the reason is for this.

![image](https://user-images.githubusercontent.com/11725674/28184782-062241da-6815-11e7-902e-e668041ccde0.png)

**Comment by petervandervoort** [comment]
Indeed, I've monitored the statistics for several days and I've seen hundreds of different device ID's for both Oregon protocol V2 and V3 but never seen device ID 5d53. These traces do come from the BTHGN129 because when I remove the batteries no new traces are created.
I think that protocol V2.2 is slightly different from V2 or V3 but although I've searched thoroughly I can't find any description of V2.2 anywhere.
I've also searched through software sources like RTL_433 that do support this Oregon sensor but can't distill the protocol from there either.
Thanks for your support so far but I think I'll just have to accept that I bought the wrong sensor and will look out for one that uses a known protocol :-)

**Comment by nlrb** [comment]
Ok, small update on this. I'm now able to get some good readings from the sensor. Looks like this one works at 1000 Hz whilst the others operate at 1024 Hz. Although this is Manchester encoding (so the clock shouldn't matter that much), the difference look to be too big for Homey. So I'm now using a special (v2.2) signal definition.

**Comment by nlrb** [comment]
Added support for protocol version 2.2 (BTHGN129 ) in app version 1.2.
