### ISSUE TITLE
Option to Disable Battery Warning

### ISSUE THREAD

**Issue by mvaneijken** [nlrb/com.weather-sensors#73]
I'm currently using this app for two Auriol weather sensors. 

Somehow the measurement of battery power is not great in these devices. That results in multiple messages into Homey saying (translated from Dutch) "Battery of Auriol sensor is almost empty" and then "Battery of Auriol sensor full". 

It would be great if the battery low notification can be configured per sensor so these messages can be reduced if needed.

**Comment by nlrb** [comment]
The app only shows the battery status the sensor reports. And Homey translates this into notifications. If it needs to be configurable, then this needs to be solved in the firmware.

BTW I have the same issue myself with some cheap batteries I got from Action. They cannot handle temperature changes and the voltage levels fluctuates too much. Easiest is to put proper  batteries in the sensor. So give that a try - I don‘t believe the sensor is at fault.

**Comment by mvaneijken** [comment]
Ok, I'll try that. Thanks for responding.
