### ISSUE TITLE
Search time seems to be too short. 

### ISSUE THREAD

**Issue by hduismann** [nlrb/com.weather-sensors#84]
I have tried to add a TFA Dostmann sensor (30.3220.02). When trying to add the sensor it seems that the search time is only a few seconds. The sensor sends only once a minute a short signal. For this reason it is extreme hard to catch the signal.

**Comment by odenis-git** [comment]
I have same problem with fresh install, for avidsen and auriol.
app start, show panel to choose sensor, and after blanck screen appear and very very quick no device found.
my two sensors are 1meter near homey.
