### ISSUE TITLE
Cresta temp meter

### ISSUE THREAD

**Issue by rpb006** [nlrb/com.weather-sensors#85]
Hi, since homey 5.0.1 update the crest temperature meter gives an error.
Can you update the app to the new homey version?

**Comment by nlrb** [comment]
This app is a v2 SDK app, which should still be supported on firmware v5. So if there is an issue, Athom should fix it.

**Comment by rpb006** [comment]
Unfortunately athom directs to the developer of the app...

**Comment by nlrb** [comment]
Do they also say what should be changed then? I wouldn't know...

**Comment by rpb006** [comment]
No. They don't. 
Any ideas how the app will recognise the meters again? In don't see them at all.

**Comment by rpb006** [comment]
After deleting and battery replacing, the app connect to the device again
