### ISSUE TITLE
Is there any possibility to add more protocols?

### ISSUE THREAD

**Issue by PatrikBrodd** [nlrb/com.weather-sensors#9]
Is there any possibility for you to add more protocols? I need the "fineoffset" protocol that my pool temp is using.
What do you mean with add a link to the protocol description?
I'm new att this.

https://github.com/merbanan/rtl_433/blob/master/src/devices/fineoffset.c

http://www.globalsources.com/si/AS/Proove-AB/6008847989756/pdtl/Temperature-Sensor/1082623540.htm

![skarmavbild 2017-09-20 kl 21 46 32](https://user-images.githubusercontent.com/32143938/30664699-e2d8a9b0-9e4e-11e7-95d5-173fa2d9ba6a.png)
![skarmavbild 2017-09-20 kl 21 42 53](https://user-images.githubusercontent.com/32143938/30664709-e8a9d13e-9e4e-11e7-8ff8-d2970db6931e.png)

**Comment by nlrb** [comment]
Thanks for the links - the code describes the protocol pretty well. However, there are 3 different protocols in there:

1. Fine Offset Electronics, WH2 Temperature/Humidity Sensor
2. Fine Offset Electronics, WH25 Temperature/Humidity/Pressure Sensor
3. Fine Offset Electronics, WH0530 Temperature/Rain Sensor

My guess is your sensor only has temperature, so you need the first one (WH2) supported?

**Comment by nlrb** [comment]
BTW: did you enable 'Alecto v3'? That one supports the WH2(A).

**Comment by PatrikBrodd** [comment]
Yes it´s only a temp sensor. 
Yes I have all the protocols enabled. the temp sensor don't turn upp.

![2017-09-23 12 34 18](https://user-images.githubusercontent.com/32143938/30772876-88f37aa6-a065-11e7-9e56-cb70457ee800.jpg)
![2017-09-23 12 34 24](https://user-images.githubusercontent.com/32143938/30772879-94156e6c-a065-11e7-9f73-b7ba45c06d36.jpg)

**Comment by nlrb** [comment]
After googling a bit it indeed looks like you need Rubicson. That is assuming the TSS340 uses the same protocol as the TSS320 (which I believe I read somewhere).

**Comment by PatrikBrodd** [comment]
Is there any possibility for you to get it to work?

**Comment by nlrb** [comment]
Can you get a recording of the signal? https://developer.athom.com/tools/signals

**Comment by nlrb** [comment]
Just checked the Rubicson protocol, but that is almost exactly the same as the Auriol protocol (Rubicson has CRC info in the last two nibbles where Auriol has humidity). So if the signal was Rubicson, you would have received the data with Auriol set to 'on'.

**Comment by PatrikBrodd** [comment]
i don´t get any data. 
The only data I get is from a outside temp I also have.
![skarmavbild 2017-09-24 kl 16 05 11](https://user-images.githubusercontent.com/32143938/30783368-30de64ec-a142-11e7-9823-f30fb95c2f78.png)

I think that I succeeded to record the signal. 
[recordings.zip](https://github.com/nlrb/com.weather-sensors/files/1327372/recordings.zip)

**Comment by nlrb** [comment]
Do you have a longer recording? Normally the signal is repeated - I don't see a repeat signal here, so hard to determine what the actual signal is.

**Comment by PatrikBrodd** [comment]
Is this better?
[recording-4.vcd.zip](https://github.com/nlrb/com.weather-sensors/files/1327465/recording-4.vcd.zip)

**Comment by nlrb** [comment]
There is no repeat signal, but the signal in there looks like Alecto v3 (48 bits). Also used by the WH2.

Can you download the statistics and add the json file here?

**Comment by PatrikBrodd** [comment]
Okej.

[stats1506281415295.json.zip](https://github.com/nlrb/com.weather-sensors/files/1327661/stats1506281415295.json.zip)

**Comment by nlrb** [comment]
Good! Consistent data in there under Alecto v3. It just fails the CRC check as it is not Alecto v3 :-). Now to figure out what the encoding is...

**Comment by nlrb** [comment]
What was the temperature at the time of capture (21:27:33 / 21:28:21)?

**Comment by PatrikBrodd** [comment]
I think it was 24'C

**Comment by PatrikBrodd** [comment]
Here is a new one
[New stats1506355720625.json.zip](https://github.com/nlrb/com.weather-sensors/files/1330141/New.stats1506355720625.json.zip)

**Comment by nlrb** [comment]
So it did find the sensor once... (as WH2A)

**Comment by PatrikBrodd** [comment]
it looks like it.
but it dosen´t show upp in the Homey.
it works fin whit my Telldus tillstick and its updating very often.

**Comment by nlrb** [comment]
Could you try to increase the sensitivity for Alectov3?

Change line 623 of `app.json` to `"sensitivity": 0.4,` and install via the CLI.

**Comment by PatrikBrodd** [comment]
Wow... that is a bit over my knowledge.. I don´t really know how to do that.. 
Is there any place I can learn how? Youtube clips maybe?
Sorry that I don´t know. I´m only a beginner att this.

**Comment by nlrb** [comment]
https://www.youtube.com/watch?v=lRZLvhF2sfk

**Comment by PatrikBrodd** [comment]
Okej. i made it! 
And the app is installed on the Homey. What now?
![skarmavbild 2017-09-25 kl 20 17 03](https://user-images.githubusercontent.com/32143938/30824052-96b540aa-a22e-11e7-99e3-d59f2045b462.png)

**Comment by nlrb** [comment]
Check if the signal is now (more) often received with the higher sensitivity.

**Comment by PatrikBrodd** [comment]
Dosen´t show.
[stats1506364273094.json.zip](https://github.com/nlrb/com.weather-sensors/files/1330455/stats1506364273094.json.zip)

**Comment by PatrikBrodd** [comment]
Now it showed upp in statistics 
[ett25-09 2041.json.zip](https://github.com/nlrb/com.weather-sensors/files/1330507/ett25-09.2041.json.zip)

**Comment by nlrb** [comment]
Ok, I see what is happening. I don't understand why it happens, but I've implemented a workaround.

Can you try the latest code from GitHub and see if that works for you?

**Comment by PatrikBrodd** [comment]
Tested. does not seem to work.
[stats1506368380452.json.zip](https://github.com/nlrb/com.weather-sensors/files/1330663/stats1506368380452.json.zip)

**Comment by nlrb** [comment]
Please make sure you use the latest code. If I put your received data in, it works.

**Comment by PatrikBrodd** [comment]
I don’t know how. 
Should I download and reinstall the entire app. Which I did or should I just replace a file or change code in a file?

**Comment by nlrb** [comment]
Yes, download all the latest code to be sure. You can check that this is part of the code in `alecto/index.js`:
```js
  if (data.length % 4 !== 0) {
    data = data.splice(data.length % 4)
  }
```
The re-install the app with `--install` or `--run`.

**Comment by PatrikBrodd** [comment]
I deleted the app on Homey. 
And reinstalled with the new one. The sensor do not turn upp in settings. After 15min I downloaded the statistics.

[stats1506441695650.json.zip](https://github.com/nlrb/com.weather-sensors/files/1333865/stats1506441695650.json.zip)

**Comment by nlrb** [comment]
Did you check the `alecto/index.js` file?

**Comment by PatrikBrodd** [comment]
yes. I found this.

![skarmavbild 2017-09-26 kl 18 24 46](https://user-images.githubusercontent.com/32143938/30871755-299aebf4-a2e8-11e7-9f8b-00b77ffe1390.png)

**Comment by nlrb** [comment]
Then the json file you sent doesn't make sense. It is impossible to have a WH2A with humidity 255 with this version.

**Comment by PatrikBrodd** [comment]
Okej. Is there any other things that I can do to help you solve this?

**Comment by nlrb** [comment]
Yes, see the request for the screenshot above.

**Comment by PatrikBrodd** [comment]
Sorry. don't understand

**Comment by nlrb** [comment]
Like this:
![image](https://user-images.githubusercontent.com/11725674/30873615-21bdde04-a2ee-11e7-8e3c-db9076c27873.png)

**Comment by PatrikBrodd** [comment]
![skarmavbild 2017-09-26 kl 19 11 20](https://user-images.githubusercontent.com/32143938/30873763-96aff594-a2ee-11e7-8991-9c86741e3373.png)

**Comment by PatrikBrodd** [comment]
Ops... sorry. now I have reinstalled it . I did something wrong.

![skarmavbild 2017-09-26 kl 19 17 48](https://user-images.githubusercontent.com/32143938/30874061-8d551bf4-a2ef-11e7-9f4a-195c0c00f4a9.png)

**Comment by PatrikBrodd** [comment]
Now it shows upp

![skarmavbild 2017-09-26 kl 19 20 22](https://user-images.githubusercontent.com/32143938/30874137-cc4b9acc-a2ef-11e7-9204-9e5f81ce3856.png)

**Comment by PatrikBrodd** [comment]
Hello again.
My sensor works fine by the way. Thank you so much for all your support!!

I have a new problem...
My friend also has ha sensor like mine (same brand). but a newer version.
I installed you're upgraded app on he´s Homey but the temp Is wrong. it shows like -6.3 degrees when its +39 degrees.

Here is his stats.


[stats1506718272464.json.zip](https://github.com/nlrb/com.weather-sensors/files/1346253/stats1506718272464.json.zip)

**Comment by nlrb** [comment]
Can you download and test the latest version of the code and check it is OK now (incl. channel)? If there is still an issue, please create a new one.

**Comment by clindh** [comment]
I have many fineoffset thermometers as well. How can I install 1.2.2 to get this new support?  The version on app store is still 1.2.1

**Comment by PatrikBrodd** [comment]
Clindh. You can find it here
https://www.youtube.com/watch?v=lRZLvhF2sfk
And here
https://snillevilla.se/miniguide-installera-appar-pa-homey-utan-att-anvanda-athom-appstore/

**Comment by clindh** [comment]
Thanks Patrik, that worked fine.
