### ISSUE TITLE
Compatible with Homey Pro (Early 2023).

### ISSUE THREAD

**Issue by haakaak** [nlrb/com.weather-sensors#99]
Hello 

Will this app be compatible with Homey Pro (Early 2023).

Thanks for the nice app

From
Håkon

**Comment by nlrb** [comment]
As I understood, the new Homey Pro will only support v3 apps. This is a v2 app, so I guess it will not work.

**Comment by pjmpessers** [comment]
Sad to hear. And there is no plan to make it SDKv3 compatiple?



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Ramón Baas ***@***.***>
Datum: 14-10-2022 21:14 (GMT+01:00)
Aan: "nlrb/com.weather-sensors" ***@***.***>
Cc: Subscribed ***@***.***>
Onderwerp: Re: [nlrb/com.weather-sensors] Compatible with Homey Pro (Early 2023). (Issue #99)


As I understood, the new Homey Pro will only support v3 apps. This is a v2 app, so I guess it will not work.

**Comment by nlrb** [comment]
No plan at the moment.

**Comment by nlrb** [comment]
Just no time

**Comment by Gammelgreggan** [comment]
Hi!
Maybe me or someone else could help updating your code?! If that would be fine with you?
I am new to node.js but work as a software developer in C, C++, Python and some Java.

Best regards Anders

**Comment by nissenhj** [comment]
> Hi! Maybe me or someone else could help updating your code?! If that would be fine with you? I am new to node.js but work as a software developer in C, C++, Python and some Java.
> 
> Best regards Anders

I understand your concern and it’s just right for you to be cautious. It’s so sad how dishonest . individual have aroused disillusionment in the minds of clients. Well I don’t know you and you don’t know me either but if we must do business , hate it or love it, there must be some degree of trust . I am a businessman and I look at a long run benefit.

**Comment by nlrb** [comment]
Anybody can make a PR.

**Comment by Albert1085** [comment]
> > Hi! Maybe me or someone else could help updating your code?! If that would be fine with you? I am new to node.js but work as a software developer in C, C++, Python and some Java.
> > Best regards Anders
> 
> Have you received any response as to whether you can help with the upgrade to SDK 3? It is initiatives like this that Athom hopes for.

I really long for a continuation and new version respectively of this absolutely useful app for Homey! Nevertheless, I know, that it will cost some time to do so, and somebody will have to be motivated.
But that looks like a plan! :-D Thanks for your initiative, Anders!
Just only think about control of various actors or devices depending on the outdoor temperature. In these days, looking towards the winter, it's all about heating control. 
This app is definitely worth to be redeveloped!
Kind regards
Albert

**Comment by pjmpessers** [comment]
That would be great, Albert. I hope nlrb is okay with that.

**Comment by Albert1085** [comment]
That would be great, indeedly! Unfortunately, I'm not a programmer in contrast to Anders. I was studying public management, and I'm working now as a civil servant. I only was teached a couple of lessons in Visual Basic in the secondary scool. But first that's quite long ago, and second, it's not really helpful in this case. ;-)

**Comment by Gammelgreggan** [comment]
> > Hi! Maybe me or someone else could help updating your code?! If that would be fine with you? I am new to node.js but work as a software developer in C, C++, Python and some Java.
> > Best regards Anders
> 
> Have you received any response as to whether you can help with the upgrade to SDK 3? It is initiatives like this that Athom hopes for.

Not so far

**Comment by nissenhj** [comment]
For me, there will be no upgrade to 2023 until all the apps I use support pro 2023. The sad thing is that until "nlrb" doesn't accept help to upgrade to SDK 3, or hands the app over to someone else. Then nothing happens! If no one else gets around to making a brand new app based on SDK 3 and which is not based on "nlrb" app.
Like now we can just try to put pressure on "nlrb" by posting here?

**Comment by nlrb** [comment]
See comment from almost a month back: https://github.com/nlrb/com.weather-sensors/issues/99#issuecomment-1291093823
Anybody can submit a Pull Request, it is open source. So stop moaning and start coding.

**Comment by nissenhj** [comment]
If I had the knowledge to code, I would have done it a long time ago!  It's just that we are different, and good at different things.  Gammelgreggan wants to help with recoding to SDK 3 but 12 days ago he writes that he hasn't received any response yet to help!?

**Comment by Gammelgreggan** [comment]
First of all I am not used to javascript. But it is not too far away from C/C++ and Java so I am not totally lost.
Second, what use to create a pullrequest if nobody will merge it later on, and release it?

**Comment by Albert1085** [comment]
> See comment from almost a month back: [#99 (comment)](https://github.com/nlrb/com.weather-sensors/issues/99#issuecomment-1291093823) Anybody can submit a Pull Request, it is open source. So stop moaning and start coding.

Calm down and carry on! Just relax, we are all stronger togehter. That's the sense of a public forum like Github. As I mentioned before, the redevelopment of an app takes some time of course. But I'm sure, that someone will be able to gain an update to sdk v3 successfully! In this aspect, thanks to nissenhj and Gammelgreggan for their efforts so far!

**Comment by Albert1085** [comment]
> For me, there will be no upgrade to 2023 until all the apps I use support pro 2023. The sad thing is that until "nlrb" doesn't accept help to upgrade to SDK 3, or hands the app over to someone else. Then nothing happens! If no one else gets around to making a brand new app based on SDK 3 and which is not based on "nlrb" app. Like now we can just try to put pressure on "nlrb" by posting here?

It's not only concerning the 2023 version of Homey Pro, but the former versions (2014, 2016, 2019) as well. This is, why Athom decided to "upgrade" all Homeys to a "Pro version", so every device got the latest updates so far.
In the end, this app is actually useless unfortunately. :-(

**Comment by csabe** [comment]
Just got the new 2023 Homey and would also love to get this good app updated to work with the 2023 version, but unfortunately don´t have the programing skills.

**Comment by mariusGundersen** [comment]
I managed to upgrade to use sdk v3 (see #102) and test it locally

**Comment by Albert1085** [comment]
Hey Marius,
thanks for your great initiative and the redevelopment of this app respectively. Is there any need to update it manually on a Homey Pro 2019? Although this issue is about the HP 2023, I'm interested how to get this update though.
Greets Albert

**Comment by Gammelgreggan** [comment]
> I managed to upgrade to use sdk v3 (see #102) and test it locally

Please commit to github and create a pullrequest for @nlrb to merge.
Then everybody will benefit from your changes.
Nice work.

**Comment by mariusGundersen** [comment]
#102 is a pull request, but I guess @nlrb is busy with other things

**Comment by Albert1085** [comment]
Hey Ramón,
thanks so much for your initiative, your efforts and finally your time spending on upgrading this very useful app to the new SDK v3 for the new Homey Pro 2023.
![grafik](https://github.com/nlrb/com.weather-sensors/assets/73784651/c90afa01-e058-4090-839a-b436695ad6d7)
In the end, very helpful of you! And I knew, it will be possible to get an upgrade done! :-)
By the way: is it possible for Homey Pro 2019 (and earlier) users to benefit from this update as well?
Greets 
Albert

**Comment by nlrb** [comment]
This app version runs on all Homey Pro’s. I run it on an HP19 as I don’t have a HP23.
